.TH r3d_encrypt_ecb "3" "24 October 2017"
.SH NAME
r3d_encrypt_ecb - Encrypt a 512 byte block of data

.SH SYNOPSIS
.B #include <libpqc/r3d.h>
.nf
.BI "void r3d_encrypt_ecb(unsigned char " *plaintext ", unsigned char " *key ", unsigned char " *ciphertext ", int " size ");

.SH DESCRIPTION

.SH RETURN VALUES

.SH SEE ALSO
