.TH r3d_encrypt_xex "3" "27 October 2017"
.SH NAME
r3d_encrypt_xex - Encrypt several blocks of data using the XEX mode of operation

.SH SYNOPSIS
.B #include <libpqc/r3d.h>
.nf
.BI "void r3d_encrypt_xex(unsigned char " *plaintext ", unsigned char " *key ", unsigned char " *ciphertext ", int " size ");

.SH DESCRIPTION

.SH RETURN VALUES

.SH SEE ALSO
