.TH r3d_encrypt_block "3" "16 October 2017"
.SH NAME
r3d_encrypt_block - Encrypt a 512 byte block of data

.SH SYNOPSIS
.B #include <libpqc/r3d.h>
.nf
.BI "void r3d_encrypt_block(unsigned char " plaintext_block[512] ", unsigned char " key[512] ", unsigned char " ciphertext_block[512] ");

.SH DESCRIPTION

.SH RETURN VALUES

.SH SEE ALSO
