.TH r3d_decrypt_ecb "3" "24 October 2017"
.SH NAME
r3d_decrypt_ecb - Decrypt a 512 byte block of data

.SH SYNOPSIS
.B #include <libpqc/r3d.h>
.nf
.BI "void r3d_decrypt_ecb(unsigned char " *ciphertext ", unsigned char " *key ", unsigned char " *plaintext ", int " size ");

.SH DESCRIPTION

.SH RETURN VALUES

.SH SEE ALSO
