.TH r3d_decrypt_block "3" "7 October 2017"
.SH NAME
r3d_decrypt_block - Decrypt a 512 byte block of data

.SH SYNOPSIS
.B #include <libpqc/r3d.h>
.br
.B void r3d_decrypt_block(unsigned char
\fIciphertext_block[512]\fR
.B , unsigned char
\fIkey[512]\fR
.B , unsigned char
\fIplaintext_block[512]\fR
.B );

.SH DESCRIPTION
