/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibPQC_LibPQC */

#ifndef _Included_LibPQC_LibPQC
#define _Included_LibPQC_LibPQC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_encrypt_ecb
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1encrypt_1ecb
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_decrypt_ecb
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1decrypt_1ecb
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_encrypt_ctr
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1encrypt_1ctr
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_decrypt_ctr
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1decrypt_1ctr
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_encrypt_ctr_mt
 * Signature: ([B[B[B[BI)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1encrypt_1ctr_1mt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_decrypt_ctr_mt
 * Signature: ([B[B[B[BI)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1decrypt_1ctr_1mt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_encrypt_xex
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1encrypt_1xex
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_decrypt_xex
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1decrypt_1xex
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_encrypt_xex_mt
 * Signature: ([B[B[BI)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1encrypt_1xex_1mt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     LibPQC_LibPQC
 * Method:    r3d_decrypt_xex_mt
 * Signature: ([B[B[BI)V
 */
JNIEXPORT void JNICALL Java_LibPQC_LibPQC_r3d_1decrypt_1xex_1mt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
