/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gabe_cryptography_LibPQC */

#ifndef _Included_gabe_cryptography_LibPQC
#define _Included_gabe_cryptography_LibPQC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gabe_cryptography_LibPQC
 * Method:    r3d_encrypt_ecb
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_gabe_cryptography_LibPQC_r3d_1encrypt_1ecb
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     gabe_cryptography_LibPQC
 * Method:    r3d_decrypt_ecb
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_gabe_cryptography_LibPQC_r3d_1decrypt_1ecb
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     gabe_cryptography_LibPQC
 * Method:    r3d_encrypt_ctr
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_gabe_cryptography_LibPQC_r3d_1encrypt_1ctr
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     gabe_cryptography_LibPQC
 * Method:    r3d_decrypt_ctr
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_gabe_cryptography_LibPQC_r3d_1decrypt_1ctr
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     gabe_cryptography_LibPQC
 * Method:    r3d_encrypt_xex
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_gabe_cryptography_LibPQC_r3d_1encrypt_1xex
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     gabe_cryptography_LibPQC
 * Method:    r3d_decrypt_xex
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_gabe_cryptography_LibPQC_r3d_1decrypt_1xex
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
