/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cryptography_LibPQC */

#ifndef _Included_cryptography_LibPQC
#define _Included_cryptography_LibPQC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cryptography_LibPQC
 * Method:    r3d_encrypt_ecb
 * Signature: (CCC)V
 */
JNIEXPORT void JNICALL Java_cryptography_LibPQC_r3d_1encrypt_1ecb
  (JNIEnv *, jobject, jchar, jchar, jchar);

/*
 * Class:     cryptography_LibPQC
 * Method:    r3d_decrypt_ecb
 * Signature: (CCC)V
 */
JNIEXPORT void JNICALL Java_cryptography_LibPQC_r3d_1decrypt_1ecb
  (JNIEnv *, jobject, jchar, jchar, jchar);

/*
 * Class:     cryptography_LibPQC
 * Method:    r3d_encrypt_ctr
 * Signature: (CCCC)V
 */
JNIEXPORT void JNICALL Java_cryptography_LibPQC_r3d_1encrypt_1ctr
  (JNIEnv *, jobject, jchar, jchar, jchar, jchar);

/*
 * Class:     cryptography_LibPQC
 * Method:    r3d_decrypt_ctr
 * Signature: (CCCC)V
 */
JNIEXPORT void JNICALL Java_cryptography_LibPQC_r3d_1decrypt_1ctr
  (JNIEnv *, jobject, jchar, jchar, jchar, jchar);

/*
 * Class:     cryptography_LibPQC
 * Method:    r3d_encrypt_xex
 * Signature: (CCC)V
 */
JNIEXPORT void JNICALL Java_cryptography_LibPQC_r3d_1encrypt_1xex
  (JNIEnv *, jobject, jchar, jchar, jchar);

/*
 * Class:     cryptography_LibPQC
 * Method:    r3d_decrypt_xex
 * Signature: (CCC)V
 */
JNIEXPORT void JNICALL Java_cryptography_LibPQC_r3d_1decrypt_1xex
  (JNIEnv *, jobject, jchar, jchar, jchar);

#ifdef __cplusplus
}
#endif
#endif
